# -*- coding: utf-8 -*-
"""ELSI_TCC_wave2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHS0gEdhx3sNuN4vXUW4_-_2wzhzCNIv
"""

Qfrom google.colab import drive
drive.mount('/content/drive')

import sys
import pandas as pd
import numpy as np
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

# Constants
import statsmodels
from scipy import constants

from statsmodels.stats.weightstats import DescrStatsW
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.formula.api as smf
from sklearn.metrics import roc_curve, auc, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# CODATA = Comitê de Dados do Conselho Internacional de Ciência from International Science Council – ISC
g = constants.g
fr_walking = .25
fr_running = .5
wave_num = 2

# Statistics
import statsmodels.api as sm
from scipy import stats

print("Versão do Python:", sys.version)
print("Versão do pandas:", pd.__version__)
print("Versão do numpy:", np.__version__)
print("Versão do statsmodels:", sm.__version__)
print("Versão do scipy:", scipy.__version__)
print("Versão do sklearn:", sklearn.__version__)

print(g)

# =========================================================
# 3. CONSTRUÇÃO DAS FÓRMULAS
# =========================================================

def montar_formula(desfecho, preditor, ajustar=False):
    formula = f"{desfecho} ~ {preditor}"
    if ajustar:
        formula += " + idade + sexo"
    return formula

# =========================================================
# 4. FUNÇÕES DE AJUSTE DOS MODELOS
# =========================================================

def rodar_ols(df, desfecho, preditor, ajustar=False):
    formula = montar_formula(desfecho, preditor, ajustar=ajustar)

    colunas = [desfecho, preditor]
    if ajustar:
        colunas += ['idade', 'sexo']

    df_modelo = df[colunas].dropna().copy()
    modelo = smf.ols(formula=formula, data=df_modelo).fit()

    return {
        'tipo_modelo': 'OLS',
        'desfecho': desfecho,
        'preditor': preditor,
        'ajustado': ajustar,
        'formula': formula,
        'n': len(df_modelo),
        'modelo': modelo
    }

def rodar_logistica(df, desfecho, preditor, ajustar=False):
    formula = montar_formula(desfecho, preditor, ajustar=ajustar)

    colunas = [desfecho, preditor]
    if ajustar:
        colunas += ['idade', 'sexo']

    df_modelo = df[colunas].dropna().copy()
    modelo = smf.logit(formula=formula, data=df_modelo).fit(disp=False)

    return {
        'tipo_modelo': 'Logística',
        'desfecho': desfecho,
        'preditor': preditor,
        'ajustado': ajustar,
        'formula': formula,
        'n': len(df_modelo),
        'modelo': modelo
    }

# =========================================================
# 5. IMPRESSÃO DOS RESULTADOS CRUDOS
# =========================================================

def imprimir_modelo_cru(nome_modelo, resultado):
    print("\n" + "=" * 120)
    print(nome_modelo)
    print("=" * 120)
    print(f"Tipo: {resultado['tipo_modelo']}")
    print(f"Fórmula: {resultado['formula']}")
    print(f"N: {resultado['n']}")
    print("-" * 120)
    print(resultado['modelo'].summary())

df = pd.read_csv(f'./drive/MyDrive/Bancos/ELSI/ELSI_wave_{wave_num}.csv')

df.head()

print(df.shape)
print(df.columns)

f_df = df[~df['mf13'].isin([888, 999])].copy()
print(f"Shape of f_df after filtering mf13 (excluding 888, 999): {f_df.shape}")

"""# Derivando velocidade
Derivada através da soma dos tempos (centésimos, segundos e minutos) e convertendo em segundos.
"""

# V1 = mf33, mf34, mf35
# V2 = mf36, mf37, mf38

f_v1 = (f_df['mf35s'] != 666) & (f_df['mf35s'] != 888) & (f_df['mf35s'] != 8888)
f_v2 = (f_df['mf38s'] != 666) & (f_df['mf38s'] != 888) & (f_df['mf38s'] != 8888)
vel_df = (f_df.loc[f_v1 & f_v2, :]).copy()

print(f'{vel_df.shape}')

vel_df['tc_3m_v_media'] = (3/vel_df['mf35s'] + 3/vel_df['mf38s']) / 2
print(vel_df['tc_3m_v_media'].describe())
print(vel_df['tc_3m_v_media'])

f_df = df.copy()
f_df['SSWS'] = vel_df['tc_3m_v_media']

"""# Derivando Tamanho dos Membros Inferiores"""

f_df = f_df[~f_df['mf13'].isin([888, 999])].copy()
print(f"Shape of f_df after filtering mf13 (excluding 888, 999): {f_df.shape}")

# Function that returns LLL (Lower Limb Length)
def get_lll(height) -> float:
  return .54 * height

f_df['lower_limb_length'] = get_lll(f_df['mf13'])

f_df['lower_limb_length'].describe()

"""# Derivando OWS"""

# OWS = Optimal Walking Speed
f_df['OWS'] = np.sqrt(fr_walking * g * (f_df['lower_limb_length']/100))
f_df['OWS'].describe()

"""# Cutt-off velocidade"""

# Calcular a velocidade máxima com o número de Froude = .5
# v = sqrt(0.5*g*LLL)
f_df['MAX_WALKING_SPEED'] = np.sqrt(fr_running*g*(f_df['lower_limb_length']/100))
f_df[['lower_limb_length', 'SSWS', 'OWS', 'MAX_WALKING_SPEED']].head()

f_df[['lower_limb_length', 'SSWS', 'OWS', 'MAX_WALKING_SPEED']].describe()

# Remove os casos em que SSWS > MAX_WALKING_SPEED
f_df = f_df[f_df['SSWS'] <= f_df['MAX_WALKING_SPEED']]

print(f'Shape after filtering: {f_df.shape}')
display(f_df[['lower_limb_length', 'SSWS', 'OWS', 'MAX_WALKING_SPEED']].describe())

v_media = f_df['SSWS']
sns.histplot(x=v_media, kde=True, bins=40)
plt.vlines(x=v_media.median(), ymin=0, ymax=1000, colors='red', linestyles='dashed', label='Mediana', alpha=0.5)
plt.vlines(x=v_media.mean(), ymin=0, ymax=1000, colors='blue', linestyles='dashed', label='Média', alpha=0.5)
plt.vlines(x=.8, ymin=0, ymax=1000, colors='black', linestyles='dashed', label='Cutt-off', alpha=0.5)
plt.legend()

plt.title('Distribuição de Velocidade')
plt.xlabel('Velocidade (m/s)')
plt.ylabel('Frequência / Densidade')

sns.boxplot(x=v_media)
plt.title('Distribuição de Velocidade')
plt.xlabel('Velocidade (m/s)')

"""# Testes de Simetria e Normalidade da Velocidade
* Q-Q Plot (Quantile-Quantile Plot)
* Teste de Anderson-Darling
"""

fig = sm.qqplot(v_media, line='s')
plt.title('Q-Q Plot para N = 8400')
plt.show()

ad_result = stats.anderson(v_media, dist='norm')
print('Teste de Anderson-Darling:')
print(f'Estatística do Teste: {ad_result.statistic}')

skew = stats.skew(v_media)
kurtosis = stats.kurtosis(v_media)

print(f'Skew: {skew}, Kurtosis: {kurtosis}')

"""# Obtendo LRI"""

# LRI = Locomotor Rehabilitation Index -> LRI = 100 * SSWS / OWS
f_df['LRI_decimal'] = f_df['SSWS'] / f_df['OWS']

f_df['LRI_decimal'].describe()

f_df['LRI'] = f_df['LRI_decimal'] * 100

f_df[['mf13', 'lower_limb_length', 'OWS', 'SSWS', 'LRI_decimal', 'LRI']].describe()

f_df[['mf13', 'lower_limb_length', 'OWS', 'SSWS', 'LRI']].hist(figsize=(10, 10), bins=40)

"""#Idade"""

f_df['idade'].describe()

"""#Multimorbidades"""

elisi_disease_codes = {
    "HAS": "n28",
    "BACK_PROBLEM": "n58",
    "DISLIPIDEMIA": "n44",
    "CATARATA": "n12",
    "ARTRITE OU REUMATISMO": "n56",
    "DEPRESSAO": "n59",
    "DIABETES MELLITUS": "n35",
    "OSTEOPOROSE": "n57",
    "INFARTO DO MIOCARDIO": "n46",
    "ANGINA DO PEITO": "n48",
    "INSUFICIENCIA CARDIACA": "n50",
    "GLAUCOMA": "n9",
    "ENFISEMA, BRONQUITE CRONICA OU DPOC": "n55",
    "ACIDENTE VASCULAR CEREBRAL (AVC, DERRAME)": "n52",
    "CANCER": "n60",
    "ASMA": "n54",
    "INSUFICIENCIA RENAL CRONICA": "n61",
    "RETINOPATIA DIABETICA": "n10",
    "DEGENERACAO MACULAR": "n11",
    "DOENCA DE PARKINSON": "n62",
    "DOENCA DE ALZHEIMER OU OUTRA DEMENCIA": "n63"
}

multimorbidades_keys = sorted(list(elisi_disease_codes.values()))

# Cria uma máscara booleana onde os valores são iguais a 1 nas colunas de multimorbidade
multimorbidity_mask = f_df[multimorbidades_keys] == 1

# Soma a máscara booleana através das colunas para obter a contagem de 1s para cada linha
f_df['n_morbidades'] = multimorbidity_mask.sum(axis=1)

# Exibe o cabeçalho do DataFrame para mostrar a nova coluna
display(f_df[['n_morbidades']])

# Verificando a distribuição para validar o poder estatístico
distribuicao = f_df['n_morbidades'].value_counts().sort_index()
print(distribuicao)

# Visualização rápida para a reunião
f_df['n_morbidades'].hist(bins=range(15))
plt.title("Distribuição de Morbidades no ELSI")
plt.show()

f_df['morbidades_menor_que_2'] = (f_df['n_morbidades'] < 2).astype(int)
f_df['morbidades_igual_a_2'] = (f_df['n_morbidades'] == 2).astype(int)
f_df['morbidades_igual_a_3'] = (f_df['n_morbidades'] == 3).astype(int)
f_df['morbidades_igual_a_4'] = (f_df['n_morbidades'] == 4).astype(int)
f_df['morbidades_igual_a_5'] = (f_df['n_morbidades'] == 5).astype(int)
f_df['morbidades_igual_a_6'] = (f_df['n_morbidades'] == 6).astype(int)
f_df['morbidades_maior_ou_igual_a_7'] = (f_df['n_morbidades'] >= 7).astype(int)

# The original morbidades>=2 and morbidades>=3 might still be useful, so keeping them.
# f_df['morbidades>=2'] = (f_df['n_morbidades'] >= 2).astype(int)
# f_df['morbidades>=3'] = (f_df['n_morbidades'] >= 3).astype(int)

morbidade_cols = ['morbidades_menor_que_2', 'morbidades_igual_a_2',
                  'morbidades_igual_a_3', 'morbidades_igual_a_4',
                  'morbidades_igual_a_5', 'morbidades_igual_a_6',
                  'morbidades_maior_ou_igual_a_7']

display(f_df[morbidade_cols].head())
print('\n'*2)
for col in morbidade_cols:
    count_ones = f_df[col].sum()
    print(f"{col} - n={count_ones}")

f_df['n_morbidades'].describe()

"""# Regressão Linear x N Morbidades"""

f_df['SSWS'].describe()

"""# Regressão Linear SSWS ~ n_morbidades"""

# Define as variáveis dependente e independente
Y = f_df['SSWS']
X = f_df['n_morbidades']

# Adiciona uma constante ao modelo (intercepto)
X = sm.add_constant(X)

# Cria e ajusta o modelo de regressão linear
model = sm.OLS(Y, X).fit()

# Exibe o resumo da regressão
print(model.summary())

# Create a scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x=f_df['n_morbidades'], y=f_df['SSWS'], alpha=0.6)

# Add the regression line
# Get the predicted values from the model
predicted_LRI = model.predict(X)
plt.plot(f_df['n_morbidades'], predicted_LRI, color='red', linewidth=2, label='Linha de Regressão')

plt.title('Relação entre Número de Multimorbidades e SSWS')
plt.xlabel('Número de Multimorbidades')
plt.ylabel('SSWS')
plt.legend()
plt.grid(True)
plt.show()

import statsmodels.api as sm

# Define as variáveis dependente e independente
Y = f_df['LRI']
X = f_df['n_morbidades']

# Adiciona uma constante ao modelo (intercepto)
X = sm.add_constant(X)

# Cria e ajusta o modelo de regressão linear
model = sm.OLS(Y, X).fit()

# Exibe o resumo da regressão
print(model.summary())

# Create a scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x=f_df['n_morbidades'], y=f_df['LRI'], alpha=0.6)

# Add the regression line
# Get the predicted values from the model
predicted_LRI = model.predict(X)
plt.plot(f_df['n_morbidades'], predicted_LRI, color='red', linewidth=2, label='Linha de Regressão')

plt.title('Relação entre Número de Multimorbidades e LRI')
plt.xlabel('Número de Multimorbidades')
plt.ylabel('LRI')
plt.legend()
plt.grid(True)
plt.show()

"""# Regressões por categorias de n_morbidades"""

morbidade_cols = ['morbidades_menor_que_2', 'morbidades_igual_a_2', 'morbidades_igual_a_3', 'morbidades_igual_a_4', 'morbidades_igual_a_5', 'morbidades_igual_a_6', 'morbidades_maior_ou_igual_a_7']
predictors = ['SSWS', 'LRI']

all_ols_results = []

for desfecho_col in morbidade_cols:
    for preditor_col in predictors:
        # Corrigido: o nome da variável no loop agora coincide com o argumento da função
        result = rodar_ols(f_df, desfecho=desfecho_col, preditor=preditor_col, ajustar=False)
        all_ols_results.append(result)
        imprimir_modelo_cru(f'OLS: {desfecho_col} ~ {preditor_col}', result)

"""## Separando `f_df` por Quartis de LRI e SSWS

Criaremos uma nova coluna `LRI_tercil` e outra `SSWS_tercil` no DataFrame `f_df` que categorizará cada observação em um dos três grupos (tercis) com base nos valores da 'LRI' e 'SSWS'. Isso dividirá o conjunto de dados em três partes aproximadamente iguais em termos de distribuição de LRI.
"""

# Separar a coluna 'LRI' em 3 tercis
f_df['LRI_tercil'] = pd.qcut(f_df['LRI'], q=3, labels=['BAIXO_LRI', 'MEDIO_LRI', 'ALTO_LRI'])

# Exibir a contagem de valores para a nova coluna
display(f_df['LRI_tercil'].value_counts())

# Exibir as primeiras linhas do DataFrame com a nova coluna
display(f_df[['LRI', 'LRI_tercil']].head())

# Separar a coluna 'LRI' em 3 tercis
f_df['SSWS_tercil'] = pd.qcut(f_df['SSWS'], q=3, labels=['BAIXO_SSWS', 'MEDIO_SSWS', 'ALTO_SSWS'])

# Exibir a contagem de valores para a nova coluna
display(f_df['SSWS_tercil'].value_counts())

# Exibir as primeiras linhas do DataFrame com a nova coluna
display(f_df[['SSWS', 'SSWS_tercil']].head())

"""## Categorização da Escolaridade

A coluna `e21` contém informações sobre o nível de escolaridade dos participantes. Para fins de análise, vamos recategorizar esses valores em grupos mais amplos, conforme as especificações fornecidas.
"""

# 1. Inspecionar a coluna 'e21'
print("Valores únicos e suas contagens na coluna 'e21':")
display(f_df['e21'].value_counts().sort_index())

# 2. Definir a função de mapeamento
def categorizar_escolaridade(e21_value):
    if e21_value in [1, 2, 3]:
        return 1
    elif e21_value == 4:
        return 2
    elif e21_value == 5:
        return 3
    elif e21_value == 6:
        return 4
    elif e21_value == 9:
        return 9

# 3. Criar a nova coluna 'escolaridade_categorizada'
f_df['escolaridade_categorizada'] = f_df['e21'].apply(categorizar_escolaridade)

# 4. Exibir a contagem de valores da nova coluna para verificar a categorização
print("\nContagem de valores na nova coluna 'escolaridade_categorizada':")
display(f_df['escolaridade_categorizada'].value_counts())

f_df['escolaridade_categorizada']

"""# N_Morbidades"""

required_columns = ['LRI', 'morbidades<2', 'morbidades=2', 'morbidades=3', 'morbidades=4', 'morbidades=5', 'morbidades=6', 'morbidades>=7']

print("Verifying existence of required columns and checking for missing values:")

for col in required_columns:
    if col in f_df.columns:
        print(f"Column '{col}' exists.")
        missing_count = f_df[col].isnull().sum()
        if missing_count > 0:
            print(f"  -> WARNING: {missing_count} missing values found in '{col}'.")
        else:
            print(f"  -> No missing values found in '{col}'.")
    else:
        print(f"ERROR: Column '{col}' does not exist in the DataFrame.")

"""**Reasoning**:
The data is confirmed to be ready. Now, I will proceed with performing the ROC analysis for 'LRI' against each of the five morbidity categories and then plot the ROC curves. This will address the core of the main task.


"""

morbidity_categories = morbidade_cols
roc_results_lri_categories = []

plt.figure(figsize=(10, 8))
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')

for category in morbidity_categories:
    y_true_cat = f_df[category]
    y_score_lri = f_df['LRI']

    fpr, tpr, _ = roc_curve(y_true_cat, y_score_lri)
    roc_auc = auc(fpr, tpr)
    roc_results_lri_categories.append({'Analysis': f'LRI vs {category}', 'AUC': roc_auc})

    plt.plot(fpr, tpr, lw=2, label=f'ROC curve (LRI vs {category}, AUC = {roc_auc:.2f})')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for LRI vs Morbidity Categories')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

df_roc_results_lri_categories = pd.DataFrame(roc_results_lri_categories)
display(df_roc_results_lri_categories)

morbidity_categories = morbidade_cols
roc_results_ssws_categories = []

plt.figure(figsize=(10, 8))
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')

for category in morbidity_categories:
    y_true_cat = f_df[category]
    y_score_ssws = f_df['SSWS']
    fpr, tpr, _ = roc_curve(y_true_cat, y_score_ssws)
    roc_auc = auc(fpr, tpr)
    roc_results_ssws_categories.append({'Analysis': f'SSWS vs {category}', 'AUC': roc_auc})

    plt.plot(fpr, tpr, lw=2, label=f'ROC curve (SSWS vs {category}, AUC = {roc_auc:.2f})')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for SSWS vs Morbidity Categories')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

df_roc_results_ssws_categories = pd.DataFrame(roc_results_ssws_categories)
display(df_roc_results_ssws_categories)

"""# Hipóteses de Variáveis (Teste)"""

# Columns for handgrip strength
handgrip_cols = ['mf27', 'mf28', 'mf29']

# Create a temporary DataFrame for calculation to avoid modifying original columns prematurely
temp_handgrip_df = f_df[handgrip_cols].copy()

# Replace values greater than 9000 with NaN in the temporary DataFrame
for col in handgrip_cols:
    temp_handgrip_df.loc[temp_handgrip_df[col] >= 555, col] = np.nan

# Calculate the mean across the cleaned handgrip columns and create the 'handgrip_mean' column in f_df
f_df['handgrip_mean'] = temp_handgrip_df.mean(axis=1)

# Define as variáveis dependente e independente
Y = f_df['n_morbidades']
X = f_df['handgrip_mean']

# Adiciona uma constante ao modelo (intercepto)
X = sm.add_constant(X.dropna())  # Remover NaNs de X antes de adicionar a constante
Y = Y[X.index] # Alinha Y com o índice de X, removendo NaNs correspondentes

# Cria e ajusta o modelo de regressão linear
model_handgrip = sm.OLS(Y, X).fit()

# Exibe o resumo da regressão
print(model_handgrip.summary())

"""# Criando variável dummy de quedas p/ rodar regressão queda binária"""

# Cria a coluna 'queda_dummy': 1 se 'n18' for 1, 0 caso contrário
f_df['queda_dummy'] = (f_df['n18'] == 1).astype(int)

# Define a variável dependente (contínua e positiva)
Y = f_df['n_morbidades']

# Define a variável independente (categórica binária)
X = f_df['queda_dummy']

# Adiciona uma constante (intercepto) ao modelo
X = sm.add_constant(X)

# Cria e ajusta o modelo de Regressão Linear (OLS)
model_n_morb_queda = sm.OLS(Y, X).fit()

# Exibe o resumo do modelo
print(model_n_morb_queda.summary())

"""# Analisando frequência AF ao menos 10 min/semana"""

# Função para categorizar a atividade física
def categorizar_atividade_fisica(valor_l9):
    if valor_l9 == 0:
        return 0  # 0 mantém 0
    elif valor_l9 == 9:
        return np.nan  # 9 se torna NaN
    elif 1 <= valor_l9 <= 7:
        return valor_l9  # Valores entre 1 e 7 são mantidos
    else:
        return np.nan # Outros valores inesperados também viram NaN

# Aplica a função para criar a nova coluna 'atividade_fisica_dummy'
f_df['atividade_fisica_dummy'] = f_df['l9'].apply(categorizar_atividade_fisica)

# Define as variáveis dependente e independente
Y = f_df['n_morbidades']
X = f_df['atividade_fisica_dummy']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean = df_temp['Y']
X_clean = df_temp['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean = sm.add_constant(X_clean)

# Cria e ajusta o modelo de regressão linear
model_morb_af = sm.OLS(Y_clean, X_clean).fit()

# Exibe o resumo da regressão
print(model_morb_af.summary())

# f_df.loc[f_df['atividade_fisica_dummy'] <= 7, 'atividade_fisica_dummy'] = \
# f_df['atividade_fisica_dummy'] * f_df['l10_2'].where(~f_df['l10_2'].isin([88, 99]))

if 'l10_2' in f_df.columns:
    # Initialize the new column with NaN
    f_df['tempo_minutos_atividade_fisica'] = np.nan

    # Apply the conditions and calculate the new column
    condition = (f_df['atividade_fisica_dummy'] <= 7) & (~f_df['l10_2'].isin([88, 99]))
    f_df.loc[condition, 'tempo_minutos_atividade_fisica'] = \
        f_df.loc[condition, 'atividade_fisica_dummy'] * f_df.loc[condition, 'l10_2']

    print("Column 'tempo_minutos_atividade_fisica' created successfully.")
    display(f_df[['atividade_fisica_dummy', 'l10_2', 'tempo_minutos_atividade_fisica']].head())
    display(f_df['tempo_minutos_atividade_fisica'].describe())
else:
    f_df['tempo_minutos_atividade_fisica'] = np.nan
    print("Warning: 'l10_2' column not found. 'tempo_minutos_atividade_fisica' column filled with NaN.")

# Define as variáveis dependente e independente
Y = f_df['SSWS']
X = f_df['tempo_minutos_atividade_fisica']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean = df_temp['Y']
X_clean = df_temp['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean = sm.add_constant(X_clean)

# Cria e ajusta o modelo de regressão linear
model_ssws_tempo_af = sm.OLS(Y_clean, X_clean).fit()

# Exibe o resumo da regressão
print("Regressão OLS: SSWS ~ tempo_minutos_atividade_fisica")
print(model_ssws_tempo_af.summary())

# Define as variáveis dependente e independente
Y = f_df['n_morbidades']
X = f_df['tempo_minutos_atividade_fisica']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean = df_temp['Y']
X_clean = df_temp['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean = sm.add_constant(X_clean)

# Cria e ajusta o modelo de regressão linear
model_n_morb_tempo_af = sm.OLS(Y_clean, X_clean).fit()

# Exibe o resumo da regressão
print("Regressão OLS: n_morbidades ~ tempo_minutos_atividade_fisica")
print(model_n_morb_tempo_af.summary())

"""# Analisando Tempo Sentado"""

# # Inspecionar a coluna 'l11'
# print("Valores únicos e suas contagens na coluna 'l11':")
# display(f_df['l11'].value_counts(dropna=False).sort_index())

# # Criar a coluna 'tempo_sentado_semana' substituindo 9999 por NaN
# f_df['tempo_sentado_semana'] = f_df['l11'].replace(9999, np.nan)

# # Converter para numérico, tratando outros códigos não-numéricos como NaN
# f_df['tempo_sentado_semana'] = pd.to_numeric(f_df['tempo_sentado_semana'], errors='coerce')

# # OLS regression
# import statsmodels.api as sm

# Y = f_df['n_morbidades']
# X = f_df['tempo_sentado_semana']

# df_temp = pd.DataFrame({'Y': Y, 'X': X}).dropna()

# Y_clean = df_temp['Y']
# X_clean = df_temp['X']

# X_clean = sm.add_constant(X_clean)

# model_morb_tempo_sentado = sm.OLS(Y_clean, X_clean).fit()

# print("\nResumo da Regressão OLS: n_morbidades vs tempo_sentado_semana")
# print(model_morb_tempo_sentado.summary())

"""# Analisando Ficar de Pé 10s"""

# Criar a variável dummy mf30_dummy
f_df['mf30_dummy'] = f_df['mf30'].apply(lambda x: x if x < 66 else np.nan)

# Define as variáveis dependente e independente
Y = f_df['SSWS']
X = f_df['mf30_dummy']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean = df_temp['Y']
X_clean = df_temp['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean = sm.add_constant(X_clean)

# Cria e ajusta o modelo de regressão linear
model_ssws_mf30 = sm.OLS(Y_clean, X_clean).fit()

# Exibe o resumo da regressão
print("Regressão OLS: SSWS ~ mf30_dummy (com NaN tratados)")
print(model_ssws_mf30.summary())

"""# SSWS ~ Semi tandem 30s (idade <= 69)"""

# Criar a variável dummy mf31_dummy
f_df['mf31_dummy'] = f_df.apply(lambda row: row['mf31'] if row['idade'] <= 69 else np.nan, axis=1)

# Define as variáveis dependente e independente
Y = f_df['SSWS']
X = f_df['mf31_dummy']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp_mf31 = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean_mf31 = df_temp_mf31['Y']
X_clean_mf31 = df_temp_mf31['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean_mf31 = sm.add_constant(X_clean_mf31)

# Cria e ajusta o modelo de regressão linear
model_ssws_mf31 = sm.OLS(Y_clean_mf31, X_clean_mf31).fit()

# Exibe o resumo da regressão
print("Regressão OLS: SSWS ~ mf31_dummy (com NaN tratados e condição de idade)")
print(model_ssws_mf31.summary())

# Define as variáveis dependente e independente
Y = f_df['n_morbidades']
X = f_df['mf31_dummy']

# Combina Y e X em um DataFrame temporário para dropar NaNs em conjunto
df_temp_morb_mf31 = pd.DataFrame({'Y': Y, 'X': X}).dropna()

Y_clean_morb_mf31 = df_temp_morb_mf31['Y']
X_clean_morb_mf31 = df_temp_morb_mf31['X']

# Adiciona uma constante ao modelo (intercepto)
X_clean_morb_mf31 = sm.add_constant(X_clean_morb_mf31)

# Cria e ajusta o modelo de regressão linear
model_morb_mf31 = sm.OLS(Y_clean_morb_mf31, X_clean_morb_mf31).fit()
resultado_robusto = model_morb_mf31.get_robustcov_results(cov_type='HC3')

# Exibe o resumo da regressão
print("Regressão OLS: n_morbidades ~ mf31_dummy (com NaN tratados e condição de idade)")
print(model_morb_mf31.summary())
print(resultado_robusto.summary())

"""# Descrição Variáveis"""

f_df[['SSWS', 'OWS', 'LRI']].describe()

ssws_less_than_0_8 = f_df[f_df['SSWS'] < 0.8]
percentage_ssws_less_than_0_8 = (len(ssws_less_than_0_8) / len(f_df)) * 100

print(f"A porcentagem de pessoas com SSWS menor que 0.8 m/s é: {percentage_ssws_less_than_0_8:.2f}%")

ssws07 = f_df[f_df['SSWS'] < 0.7]
percentage_ssws_less_than_0_7 = (len(ssws07) / len(f_df)) * 100

print(f"A porcentagem de pessoas com SSWS menor que 0.7 m/s é: {percentage_ssws_less_than_0_7:.2f}%")

ssws06 = f_df[f_df['SSWS'] < 0.6]
percentage_ssws_less_than_0_6 = (len(ssws06) / len(f_df)) * 100

print(f"A porcentagem de pessoas com SSWS menor que 0.6 m/s é: {percentage_ssws_less_than_0_6:.2f}%")

# 1. Definindo os pontos de corte sugeridos
cortes = [2, 3, 4]

results = []

for c in cortes:
    target = f_df['n_morbidades'] >= c

    # Modelo com SSWS (Velocidade Absoluta)
    X_ssws = sm.add_constant(f_df[['SSWS', 'idade', 'sexo']])
    mod_ssws = sm.Logit(target, X_ssws).fit(disp=0)
    auc_ssws = roc_auc_score(target, mod_ssws.predict(X_ssws))

    # Modelo com LRI (Seu índice ajustado)
    X_lri = sm.add_constant(f_df[['LRI', 'idade', 'sexo']])
    mod_lri = sm.Logit(target, X_lri).fit(disp=0)
    auc_lri = roc_auc_score(target, mod_lri.predict(X_lri))

    results.append({'Corte': f'>={c}', 'AUC_SSWS': auc_ssws, 'AUC_LRI': auc_lri})

# Exibindo a comparação de desempenho
df_res = pd.DataFrame(results)
print(df_res)

# Verificando o n de cada sexo para saber se é possível estratificar por sexo
f_df['sexo'].value_counts()

"""# Testando Multicolinearidade com VIF
LRI || SSWS + idade + sexo
"""

# Preparando os dataframes (removendo NaNs das colunas de interesse)
cols_base = ['idade', 'sexo', 'n_morbidades']
df_vif_ssws = f_df[cols_base + ['SSWS']].dropna()
df_vif_lri = f_df[cols_base + ['LRI']].dropna()

def interpretar_vif(vif):
  if vif < 5:
      return 'aceitável'
  elif vif < 10:
      return 'atenção'
  else:
      return 'alta multicolinearidade'


def calcular_vif(df, col_marcha):
    # Definimos os preditores (X)
    X = df[[col_marcha, 'idade', 'sexo']]
    X = sm.add_constant(X) # Adiciona o intercepto para o cálculo correto

    vif_data = pd.DataFrame()
    vif_data["Variável"] = X.columns
    vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    return vif_data

print("--- VIF: Modelo SSWS ---")
print(calcular_vif(df_vif_ssws, 'SSWS'))

print("\n--- VIF: Modelo LRI ---")
print(calcular_vif(df_vif_lri, 'LRI'))

"""# Estratificação em categorias de doenças"""

# =========================================================
# 1. DEFINIÇÃO DOS GRUPOS DE DOENÇAS
# =========================================================

grupo_0 = {
    'n9':  'glaucoma',
    'n10': 'retinopatia_diabetica',
    'n11': 'degeneracao_macular',
    'n12': 'catarata',
    'n52': 'avc_derrame',
    'n56': 'artrite_reumatismo',
    'n57': 'osteoporose',
    'n58': 'problema_cronico_coluna',
    'n62': 'doenca_parkinson',
    'n63': 'doenca_alzheimer_ou_demencia'
}

grupo_1 = {
    'n28': 'hipertensao_arterial',
    'n46': 'infarto_miocardio',
    'n48': 'angina_peito',
    'n50': 'insuficiencia_cardiaca',
    'n54': 'asma',
    'n55': 'dpoc_bronquite_enfisema'
}

grupo_2 = {
    'n35': 'diabetes_mellitus',
    'n44': 'dislipidemia',
    'n59': 'depressao',
    'n60': 'cancer',
    'n61': 'insuficiencia_renal_cronica'
}

# =========================================================
# 2. LISTAS DE COLUNAS EXISTENTES NO DATAFRAME
# =========================================================

cols_g0 = [c for c in grupo_0.keys() if c in f_df.columns]
cols_g1 = [c for c in grupo_1.keys() if c in f_df.columns]
cols_g2 = [c for c in grupo_2.keys() if c in f_df.columns]

print("Colunas do grupo 0 encontradas:", cols_g0)
print("Colunas do grupo 1 encontradas:", cols_g1)
print("Colunas do grupo 2 encontradas:", cols_g2)

# =========================================================
# 3. PADRONIZAÇÃO DAS VARIÁVEIS DE DOENÇA
#    Ajuste esperado:
#    1 = possui
#    0 = não possui
#    9 = missing / não sabe / não respondeu
# =========================================================

todas_colunas = cols_g0 + cols_g1 + cols_g2

for col in todas_colunas:
    f_df[col] = pd.to_numeric(f_df[col], errors='coerce')
    f_df[col] = f_df[col].replace(9, np.nan)
    f_df[col] = f_df[col].map({0: 0, 1: 1})

# =========================================================
# 4. CRIAÇÃO DAS 3 COLUNAS BINÁRIAS DOS GRUPOS
# =========================================================

f_df['grupo_0_neuro_oftalmo_musculoesqueleticas'] = (
    f_df[cols_g0].fillna(0).max(axis=1)
).astype(int)

f_df['grupo_1_cardiorrespiratorias'] = (
    f_df[cols_g1].fillna(0).max(axis=1)
).astype(int)

f_df['grupo_2_outras'] = (
    f_df[cols_g2].fillna(0).max(axis=1)
).astype(int)

# =========================================================
# 4.1. CRIAÇÃO DAS 3 COLUNAS DE SOMA DE MORBIDADES POR GRUPO
# =========================================================

f_df['soma_grupo_0_neuro_oftalmo_musculoesqueleticas'] = (
    f_df[cols_g0].fillna(0).sum(axis=1)
).astype(int)

f_df['soma_grupo_1_cardiorrespiratorias'] = (
    f_df[cols_g1].fillna(0).sum(axis=1)
).astype(int)

f_df['soma_grupo_2_outras'] = (
    f_df[cols_g2].fillna(0).sum(axis=1)
).astype(int)

# =========================================================
# 5. CONFERÊNCIA DAS FREQUÊNCIAS
# =========================================================

print("\nFrequência por grupo:")
print(
    f_df[
        [
            'grupo_0_neuro_oftalmo_musculoesqueleticas',
            'grupo_1_cardiorrespiratorias',
            'grupo_2_outras',
            'soma_grupo_0_neuro_oftalmo_musculoesqueleticas',
            'soma_grupo_1_cardiorrespiratorias',
            'soma_grupo_2_outras'
        ]
    ].sum()
)

# =========================================================
# 6. CONFERÊNCIA DAS COMBINAÇÕES ENTRE GRUPOS
# =========================================================

print("\nCombinações entre grupos:")
print(
    f_df[
        [
            'grupo_0_neuro_oftalmo_musculoesqueleticas',
            'grupo_1_cardiorrespiratorias',
            'grupo_2_outras'
        ]
    ].value_counts().sort_index()
)

# =========================================================
# 7. VISUALIZAÇÃO RÁPIDA
# =========================================================

display(
    f_df[
        [
            'grupo_0_neuro_oftalmo_musculoesqueleticas',
            'grupo_1_cardiorrespiratorias',
            'grupo_2_outras',
            'soma_grupo_0_neuro_oftalmo_musculoesqueleticas',
            'soma_grupo_1_cardiorrespiratorias',
            'soma_grupo_2_outras'
        ]
    ].head(10)
)

# =========================================================
# 1. DEFINIÇÃO DOS GRUPOS DE DOENÇAS
# =========================================================

GRUPO_0 = {
    'n9':  'glaucoma',
    'n10': 'retinopatia_diabetica',
    'n11': 'degeneracao_macular',
    'n12': 'catarata',
    'n52': 'avc_derrame',
    'n56': 'artrite_reumatismo',
    'n57': 'osteoporose',
    'n58': 'problema_cronico_coluna',
    'n62': 'doenca_parkinson',
    'n63': 'doenca_alzheimer_ou_outra_demencia'
}

GRUPO_1 = {
    'n28': 'hipertensao_arterial',
    'n46': 'infarto_miocardio',
    'n48': 'angina_peito',
    'n50': 'insuficiencia_cardiaca',
    'n54': 'asma',
    'n55': 'dpoc_bronquite_enfisema'
}

GRUPO_2 = {
    'n35': 'diabetes_mellitus',
    'n44': 'dislipidemia',
    'n59': 'depressao',
    'n60': 'cancer',
    'n61': 'insuficiencia_renal_cronica'
}

# =========================================================
# 2. PREPARAÇÃO DOS GRUPOS BINÁRIOS
# =========================================================

def preparar_grupos_morbidade(df):
    df = df.copy()

    cols_g0 = [c for c in GRUPO_0.keys() if c in df.columns]
    cols_g1 = [c for c in GRUPO_1.keys() if c in df.columns]
    cols_g2 = [c for c in GRUPO_2.keys() if c in df.columns]

    todas_colunas = cols_g0 + cols_g1 + cols_g2

    for col in todas_colunas:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].replace(9, np.nan)
        df[col] = df[col].map({0: 0, 1: 1})

    df['grupo_0_neuro_oftalmo_musculoesqueleticas'] = (
        df[cols_g0].fillna(0).max(axis=1)
    ).astype(int)

    df['grupo_1_cardiorrespiratorias'] = (
        df[cols_g1].fillna(0).max(axis=1)
    ).astype(int)

    df['grupo_2_outras'] = (
        df[cols_g2].fillna(0).max(axis=1)
    ).astype(int)

    # Add continuous sum columns
    df['soma_grupo_0_neuro_oftalmo_musculoesqueleticas'] = (
        df[cols_g0].fillna(0).sum(axis=1)
    ).astype(int)

    df['soma_grupo_1_cardiorrespiratorias'] = (
        df[cols_g1].fillna(0).sum(axis=1)
    ).astype(int)

    df['soma_grupo_2_outras'] = (
        df[cols_g2].fillna(0).sum(axis=1)
    ).astype(int)

    return df

# =========================================================
# 6. EXTRAÇÃO DAS MÉTRICAS PARA TABELA-RESUMO
# =========================================================

def extrair_metricas_modelo(resultado):
    modelo = resultado['modelo']
    preditor = resultado['preditor']

    linha = {
        'tipo_modelo': resultado['tipo_modelo'],
        'desfecho': resultado['desfecho'],
        'preditor': resultado['preditor'],
        'ajustado': resultado['ajustado'],
        'formula': resultado['formula'],
        'n': resultado['n'],
        'coef': np.nan,
        'std_err': np.nan,
        'stat': np.nan,
        'p_value': np.nan,
        'ic95_inf': np.nan,
        'ic95_sup': np.nan,
        'r_squared': np.nan,
        'r_squared_ajustado': np.nan,
        'pseudo_r_squared': np.nan,
        'aic': np.nan,
        'bic': np.nan,
        'odds_ratio': np.nan,
        'or_ic95_inf': np.nan,
        'or_ic95_sup': np.nan
    }

    if preditor in modelo.params.index:
        linha['coef'] = modelo.params[preditor]
        linha['std_err'] = modelo.bse[preditor]
        linha['p_value'] = modelo.pvalues[preditor]

        conf = modelo.conf_int().loc[preditor]
        linha['ic95_inf'] = conf[0]
        linha['ic95_sup'] = conf[1]

        # Em OLS é t; em Logit o statsmodels expõe como z via tvalues
        linha['stat'] = modelo.tvalues[preditor]

    if resultado['tipo_modelo'] == 'OLS':
        linha['r_squared'] = modelo.rsquared
        linha['r_squared_ajustado'] = modelo.rsquared_adj
        linha['aic'] = modelo.aic
        linha['bic'] = modelo.bic

    elif resultado['tipo_modelo'] == 'Logística':
        linha['pseudo_r_squared'] = modelo.prsquared
        linha['aic'] = modelo.aic
        linha['bic'] = modelo.bic

        if preditor in modelo.params.index:
            linha['odds_ratio'] = np.exp(modelo.params[preditor])
            linha['or_ic95_inf'] = np.exp(linha['ic95_inf'])
            linha['or_ic95_sup'] = np.exp(linha['ic95_sup'])

    return linha

# =========================================================
# 7. FUNÇÃO PRINCIPAL PARA RODAR TODAS AS REGRESSÕES (Refactored)
# =========================================================

def rodar_todas_regressoes(df):
    ols_results_raw = []
    logistic_results_raw = []

    predictors = ['SSWS', 'LRI']

    # OLS Dependent Variables (continuous)
    ols_desfechos = ['n_morbidades'] + [
        'soma_grupo_0_neuro_oftalmo_musculoesqueleticas',
        'soma_grupo_1_cardiorrespiratorias',
        'soma_grupo_2_outras'
    ]

    # Logistic Dependent Variables (binary)
    logistic_desfechos = [
        'grupo_0_neuro_oftalmo_musculoesqueleticas',
        'grupo_1_cardiorrespiratorias',
        'grupo_2_outras'
    ] + [
        'morbidades_menor_que_2', 'morbidades_igual_a_2',
        'morbidades_igual_a_3', 'morbidades_igual_a_4',
        'morbidades_igual_a_5', 'morbidades_igual_a_6',
        'morbidades_maior_ou_igual_a_7'
    ]

    # Run OLS Regressions
    for desfecho in ols_desfechos:
        for preditor in predictors:
            # Non-adjusted
            ols_results_raw.append(rodar_ols(df, desfecho, preditor, ajustar=False))
            # Adjusted
            ols_results_raw.append(rodar_ols(df, desfecho, preditor, ajustar=True))

    # Run Logistic Regressions
    for desfecho in logistic_desfechos:
        for preditor in predictors:
            # Non-adjusted
            logistic_results_raw.append(rodar_logistica(df, desfecho, preditor, ajustar=False))
            # Adjusted
            logistic_results_raw.append(rodar_logistica(df, desfecho, preditor, ajustar=True))

    # Extract metrics and create DataFrames
    resultados_ols = pd.DataFrame([extrair_metricas_modelo(r) for r in ols_results_raw])
    resultados_logistica = pd.DataFrame([extrair_metricas_modelo(r) for r in logistic_results_raw])

    # Define column orders for OLS and Logistic results
    ols_ordem_colunas = [
        'tipo_modelo', 'desfecho', 'preditor', 'ajustado', 'formula', 'n',
        'coef', 'std_err', 'stat', 'p_value',
        'ic95_inf', 'ic95_sup',
        'r_squared', 'r_squared_ajustado',
        'aic', 'bic'
    ]
    logistic_ordem_colunas = [
        'tipo_modelo', 'desfecho', 'preditor', 'ajustado', 'formula', 'n',
        'coef', 'std_err', 'stat', 'p_value',
        'ic95_inf', 'ic95_sup',
        'pseudo_r_squared',
        'aic', 'bic',
        'odds_ratio', 'or_ic95_inf', 'or_ic95_sup'
    ]

    resultados_ols = resultados_ols[ols_ordem_colunas].copy()
    resultados_logistica = resultados_logistica[logistic_ordem_colunas].copy()

    # Round numerical columns for clean display
    colunas_numericas_para_arredondar = [
        'coef', 'std_err', 'stat', 'p_value',
        'ic95_inf', 'ic95_sup',
        'r_squared', 'r_squared_ajustado', 'pseudo_r_squared',
        'aic', 'bic',
        'odds_ratio', 'or_ic95_inf', 'or_ic95_sup'
    ]

    for col in colunas_numericas_para_arredondar:
        if col in resultados_ols.columns:
            resultados_ols[col] = resultados_ols[col].round(4)
        if col in resultados_logistica.columns:
            resultados_logistica[col] = resultados_logistica[col].round(4)

    return resultados_ols, resultados_logistica

# =========================================================
# 8. EXECUÇÃO (Refactored)
# =========================================================

f_df_modelo = preparar_grupos_morbidade(f_df) # Assuming f_df and preparar_grupos_morbidade are defined

# Call the refactored function
resultados_ols, resultados_logistica = rodar_todas_regressoes(f_df_modelo)

# =========================================================
# 9. MOSTRAR OS RESULTADOS SEPARADAMENTE
# =========================================================

print("\n" + "=" * 120)
print("TABELA RESUMO - REGRESSÕES OLS")
print("=" * 120)
display(resultados_ols)

print("\n" + "=" * 120)
print("TABELA RESUMO - REGRESSÕES LOGÍSTICAS")
print("=" * 120)
display(resultados_logistica)

"""# Tabelas TCC e Resumo"""

# =========================================================
# 1. EXTRAIR MÉTRICAS DE CADA MODELO EM FORMATO CORRETO
# =========================================================

def extrair_metricas_modelo(resultado):
    modelo = resultado['modelo']
    preditor = resultado['preditor']

    linha = {
        'tipo_modelo': resultado['tipo_modelo'],
        'desfecho': resultado['desfecho'],
        'preditor': resultado['preditor'],
        'ajustado': resultado['ajustado'],
        'formula': resultado['formula'],
        'n': resultado['n'],
        'coef': np.nan,
        'std_err': np.nan,
        'stat': np.nan,
        'p_value': np.nan,
        'ic95_inf': np.nan,
        'ic95_sup': np.nan,
        'r_squared': np.nan,
        'r_squared_ajustado': np.nan,
        'pseudo_r_squared': np.nan,
        'aic': np.nan,
        'bic': np.nan,
        'odds_ratio': np.nan,
        'or_ic95_inf': np.nan,
        'or_ic95_sup': np.nan
    }

    if preditor in modelo.params.index:
        linha['coef'] = modelo.params[preditor]
        linha['std_err'] = modelo.bse[preditor]
        linha['p_value'] = modelo.pvalues[preditor]

        conf = modelo.conf_int().loc[preditor]
        linha['ic95_inf'] = conf[0]
        linha['ic95_sup'] = conf[1]

        # Em OLS é t; em Logit o statsmodels expõe como z via tvalues
        linha['stat'] = modelo.tvalues[preditor]

    if resultado['tipo_modelo'] == 'OLS':
        linha['r_squared'] = modelo.rsquared
        linha['r_squared_ajustado'] = modelo.rsquared_adj
        linha['aic'] = modelo.aic
        linha['bic'] = modelo.bic

    elif resultado['tipo_modelo'] == 'Logística':
        linha['pseudo_r_squared'] = modelo.prsquared
        linha['aic'] = modelo.aic
        linha['bic'] = modelo.bic

        if preditor in modelo.params.index:
            linha['odds_ratio'] = np.exp(modelo.params[preditor])
            linha['or_ic95_inf'] = np.exp(linha['ic95_inf'])
            linha['or_ic95_sup'] = np.exp(linha['ic95_sup'])

    return linha

# =========================================================
# 2. RECRIAR TABELA_RESUMO CORRETAMENTE
# =========================================================

# Concatenate the OLS and Logistic results into a single DataFrame
tabela_resumo = pd.concat([resultados_ols, resultados_logistica], ignore_index=True)

print("Colunas recriadas corretamente:")
print(tabela_resumo.columns.tolist())

# =========================================================
# 3. INTERPRETAÇÃO AUTOMÁTICA
# =========================================================

def interpretar_efeito(linha):
    preditor = linha['preditor']
    desfecho = linha['desfecho']
    tipo_modelo = linha['tipo_modelo']
    coef = linha['coef']
    p_value = linha['p_value']

    if pd.isna(coef) or pd.isna(p_value):
        return 'interpretação indisponível'

    if p_value >= 0.05:
        return f'sem associação estatisticamente significativa entre {preditor} e {desfecho}'

    if tipo_modelo == 'OLS':
        if coef > 0:
            return f'maior {preditor} associado a maior {desfecho}'
        elif coef < 0:
            return f'maior {preditor} associado a menor {desfecho}'
        else:
            return f'ausência de efeito aparente de {preditor} sobre {desfecho}'

    if tipo_modelo == 'Logística':
        if coef > 0:
            return f'maior {preditor} associado a maior chance de {desfecho}'
        elif coef < 0:
            return f'maior {preditor} associado a menor chance de {desfecho}'
        else:
            return f'ausência de efeito aparente de {preditor} sobre {desfecho}'

    return 'interpretação não classificada'

def classificar_direcao(linha):
    coef = linha['coef']
    p_value = linha['p_value']

    if pd.isna(coef) or pd.isna(p_value):
        return 'indeterminado'
    if p_value >= 0.05:
        return 'não significativo'
    if coef > 0:
        return 'positivo'
    if coef < 0:
        return 'negativo'
    return 'nulo'

def classificar_significancia(p):
    if pd.isna(p):
        return 'indisponível'
    elif p < 0.001:
        return 'p<0.001'
    elif p < 0.01:
        return 'p<0.01'
    elif p < 0.05:
        return 'p<0.05'
    else:
        return 'ns'

tabela_resumo['direcao_efeito'] = tabela_resumo.apply(classificar_direcao, axis=1)
tabela_resumo['significancia'] = tabela_resumo['p_value'].apply(classificar_significancia)
tabela_resumo['interpretacao_automatica'] = tabela_resumo.apply(interpretar_efeito, axis=1)

"""# Exibição dos Dados"""

cols_ols = ['tipo_modelo', 'desfecho', 'preditor', 'ajustado', 'n', 'coef', 'std_err', 'stat', 'p_value', 'r_squared', 'r_squared_ajustado', 'aic', 'bic', 'direcao_efeito', 'significancia', 'interpretacao_automatica']
cols_log = ['tipo_modelo', 'desfecho', 'preditor', 'ajustado', 'n', 'coef', 'std_err', 'stat', 'p_value', 'pseudo_r_squared', 'odds_ratio', 'or_ic95_inf', 'or_ic95_sup', 'aic', 'bic', 'direcao_efeito', 'significancia', 'interpretacao_automatica']

print('\n' + '=' * 120)
print('INTERPRETAÇÃO DOS RESULTADOS - REGRESSÕES OLS')
print('=' * 120)
# Filter and select only OLS relevant columns
tabela_ols = tabela_resumo[tabela_resumo['tipo_modelo'] == 'OLS'][cols_ols].copy()
display(tabela_ols)

print('\n' + '=' * 120)
print('INTERPRETAÇÃO DOS RESULTADOS - REGRESSÕES LOGÍSTICAS')
print('=' * 120)
# Filter and select only Logistic relevant columns
tabela_logistica = tabela_resumo[tabela_resumo['tipo_modelo'] == 'Logística'][cols_log].copy()
display(tabela_logistica)

"""# Regressão SSWS x LRI"""

resultado = rodar_ols(f_df, desfecho='LRI', preditor='SSWS')
print(resultado['modelo'].summary())

print(f'Morbidades: {round(f_df['n_morbidades'].mean(), 2)} +- {round(f_df['n_morbidades'].std(), 2)}')

print(f'SSWS: {round(f_df['SSWS'].mean(), 2)} +- {round(f_df['SSWS'].std(), 2)}')

print(f'LRI: {round(f_df['LRI'].mean(), 2)} +- {round(f_df['LRI'].std(), 2)}')

Y = f_df['n_morbidades']
X = f_df['SSWS']

X = sm.add_constant(X)

# Create and fit the Poisson regression model
poisson_model = sm.Poisson(Y, X)
poisson_results = poisson_model.fit()

# Display the regression summary
print("Poisson Regression Results: n_morbidades ~ SSWS")
print(poisson_results.summary())

# output_path = './drive/MyDrive/f_df_export.csv'
# f_df.to_csv(output_path, index=False)
# print(f'DataFrame f_df exported successfully to: {output_path}')

output_path_ols = './drive/MyDrive/f_df_result_ols.csv'
tabela_ols.to_csv(output_path_ols, index=False)
print(f'DataFrame resultados_ols exported successfully to: {output_path_ols}')

output_path_logistica = './drive/MyDrive/f_df_result_logistica.csv'
tabela_logistica.to_csv(output_path_logistica, index=False)
print(f'DataFrame resultados_logistica exported successfully to: {output_path_logistica}')

"""## Relatório de Variáveis Utilizadas no Estudo

Este relatório detalha as variáveis empregadas na análise, discriminando entre as variáveis originais do dataset ELSI e as variáveis derivadas ao longo do estudo, juntamente com suas aplicações primárias.

### Variáveis Originais do Dataset ELSI:

*   **`mf13`**: Altura, utilizada para filtragem e para derivar o comprimento dos membros inferiores.
*   **`mf35s`, `mf38s`**: Tempos para cálculo da velocidade de caminhada.
*   **`idade`**: Idade, empregada como preditor em modelos ajustados e para filtragem.
*   **`sexo`**: Sexo, utilizada como preditor em modelos ajustados.
*   **`n9` a `n12`, `n28`, `n35`, `n44`, `n46`, `n48`, `n50`, `n52`, `n54` a `n63`**: Códigos individuais de doenças, usados para calcular `n_morbidades` e categorizar grupos de doenças.
*   **`e21`**: Nível de escolaridade, usado para criar `escolaridade_categorizada`.
*   **`mf27`, `mf28`, `mf29`**: Medidas de força de preensão manual, usadas para derivar `handgrip_mean`.
*   **`n18`**: Histórico de quedas, usado para criar `queda_dummy`.
*   **`l9`**: Frequência de atividade física, usada para derivar `atividade_fisica_dummy`.
*   **`l10_2`**: Duração da atividade física, usada em conjunto com `l9` para derivar `tempo_minutos_atividade_fisica`.
*   **`mf30`**: Tempo para levantar e sentar da cadeira 5 vezes, usado para criar `mf30_dummy`.
*   **`mf31`**: Tempo para manter o equilíbrio na posição semi-tandem, usado para criar `mf31_dummy`.

### Variáveis Derivadas:

*   **`tc_3m_v_media`**: Cálculo intermediário para a velocidade média de caminhada.
*   **`SSWS`** (Self-Selected Walking Speed - Velocidade de Caminhada Auto-Selecionada): Variável independente primária, também usada como variável dependente em alguns modelos, derivada de `mf35s` e `mf38s`.
*   **`lower_limb_length`**: Comprimento dos membros inferiores, derivado de `mf13`.
*   **`OWS`** (Optimal Walking Speed - Velocidade Ótima de Caminhada): Derivada de `lower_limb_length`.
*   **`MAX_WALKING_SPEED`**: Velocidade máxima de caminhada, derivada de `lower_limb_length`.
*   **`LRI_decimal`**: Cálculo intermediário para o Índice de Reabilitação Locomotor (LRI).
*   **`LRI`** (Locomotor Rehabilitation Index - Índice de Reabilitação Locomotor): Variável independente primária, derivada de `SSWS` e `OWS`.
*   **`n_morbidades`**: Número total de morbidades, derivado dos códigos individuais de doenças, usado como variável dependente.
*   **`morbidades_menor_que_2`**, **`morbidades_igual_a_2`**, ..., **`morbidades_maior_ou_igual_a_7`**: Indicadores binários para contagens específicas de morbidades, utilizados como variáveis dependentes em regressões logísticas.
*   **`LRI_tercil`**: Versão categórica do LRI, dividida em tercis (baixo, médio, alto).
*   **`SSWS_tercil`**: Versão categórica do SSWS, dividida em tercis.
*   **`escolaridade_categorizada`**: Representação categórica do nível de escolaridade, derivada de `e21`.
*   **`handgrip_mean`**: Média da força de preensão manual, derivada de `mf27`, `mf28`, `mf29`.
*   **`queda_dummy`**: Variável binária indicando se o participante sofreu uma queda, derivada de `n18`.
*   **`atividade_fisica_dummy`**: Representação categórica da frequência de atividade física, derivada de `l9`.
*   **`tempo_minutos_atividade_fisica`**: Medida quantitativa do tempo de atividade física, derivada de `l9` e `l10_2`.
*   **`mf30_dummy`**: Valor processado de `mf30`.
*   **`mf31_dummy`**: Valor processado de `mf31`, considerando a idade.
*   **`grupo_0_neuro_oftalmo_musculoesqueleticas`**, **`grupo_1_cardiorrespiratorias`**, **`grupo_2_outras`**: Indicadores binários para a presença de qualquer doença dentro de grupos específicos pré-definidos.
*   **`soma_grupo_0_neuro_oftalmo_musculoesqueleticas`**, **`soma_grupo_1_cardiorrespiratorias`**, **`soma_grupo_2_outras`**: Soma das doenças dentro de cada grupo específico, usadas como variáveis dependentes em regressões OLS.

"""

variable_report_content = """
## Relatório de Variáveis Utilizadas no Estudo

Este relatório detalha as variáveis empregadas na análise, discriminando entre as variáveis originais do dataset ELSI e as variáveis derivadas ao longo do estudo, juntamente com suas aplicações primárias.

### Variáveis Originais do Dataset ELSI:

*   **`mf13`**: Altura, utilizada para filtragem e para derivar o comprimento dos membros inferiores.
*   **`mf35s`, `mf38s`**: Tempos para cálculo da velocidade de caminhada.
*   **`idade`**: Idade, empregada como preditor em modelos ajustados e para filtragem.
*   **`sexo`**: Sexo, utilizada como preditor em modelos ajustados.
*   **`n9` a `n12`, `n28`, `n35`, `n44`, `n46`, `n48`, `n50`, `n52`, `n54` a `n63`**: Códigos individuais de doenças, usados para calcular `n_morbidades` e categorizar grupos de doenças.
*   **`e21`**: Nível de escolaridade, usado para criar `escolaridade_categorizada`.
*   **`mf27`, `mf28`, `mf29`**: Medidas de força de preensão manual, usadas para derivar `handgrip_mean`.
*   **`n18`**: Histórico de quedas, usado para criar `queda_dummy`.
*   **`l9`**: Frequência de atividade física, usada para derivar `atividade_fisica_dummy`.
*   **`l10_2`**: Duração da atividade física, usada em conjunto com `l9` para derivar `tempo_minutos_atividade_fisica`.
*   **`mf30`**: Tempo para levantar e sentar da cadeira 5 vezes, usado para criar `mf30_dummy`.
*   **`mf31`**: Tempo para manter o equilíbrio na posição semi-tandem, usado para criar `mf31_dummy`.

### Variáveis Derivadas:

*   **`tc_3m_v_media`**: Cálculo intermediário para a velocidade média de caminhada.
*   **`SSWS`** (Self-Selected Walking Speed - Velocidade de Caminhada Auto-Selecionada): Variável independente primária, também usada como variável dependente em alguns modelos, derivada de `mf35s` e `mf38s`.
*   **`lower_limb_length`**: Comprimento dos membros inferiores, derivado de `mf13`.
*   **`OWS`** (Optimal Walking Speed - Velocidade Ótima de Caminhada): Derivada de `lower_limb_length`.
*   **`MAX_WALKING_SPEED`**: Velocidade máxima de caminhada, derivada de `lower_limb_length`.
*   **`LRI_decimal`**: Cálculo intermediário para o Índice de Reabilitação Locomotor (LRI).
*   **`LRI`** (Locomotor Rehabilitation Index - Índice de Reabilitação Locomotor): Variável independente primária, derivada de `SSWS` e `OWS`.
*   **`n_morbidades`**: Número total de morbidades, derivado dos códigos individuais de doenças, usado como variável dependente.
*   **`morbidades_menor_que_2`**, **`morbidades_igual_a_2`**, ..., **`morbidades_maior_ou_igual_a_7`**: Indicadores binários para contagens específicas de morbidades, utilizados como variáveis dependentes em regressões logísticas.
*   **`LRI_tercil`**: Versão categórica do LRI, dividida em tercis (baixo, médio, alto).
*   **`SSWS_tercil`**: Versão categórica do SSWS, dividida em tercis.
*   **`escolaridade_categorizada`**: Representação categórica do nível de escolaridade, derivada de `e21`.
*   **`handgrip_mean`**: Média da força de preensão manual, derivada de `mf27`, `mf28`, `mf29`.
*   **`queda_dummy`**: Variável binária indicando se o participante sofreu uma queda, derivada de `n18`.
*   **`atividade_fisica_dummy`**: Representação categórica da frequência de atividade física, derivada de `l9`.
*   **`tempo_minutos_atividade_fisica`**: Medida quantitativa do tempo de atividade física, derivada de `l9` e `l10_2`.
*   **`mf30_dummy`**: Valor processado de `mf30`.
*   **`mf31_dummy`**: Valor processado de `mf31`, considerando a idade.
*   **`grupo_0_neuro_oftalmo_musculoesqueleticas`**, **`grupo_1_cardiorrespiratorias`**, **`grupo_2_outras`**: Indicadores binários para a presença de qualquer doença dentro de grupos específicos pré-definidos.
*   **`soma_grupo_0_neuro_oftalmo_musculoesqueleticas`**, **`soma_grupo_1_cardiorrespiratorias`**, **`soma_grupo_2_outras`**: Soma das doenças dentro de cada grupo específico, usadas como variáveis dependentes em regressões OLS.
"""

output_path_md = './drive/MyDrive/relatorio_variaveis.md'

with open(output_path_md, 'w', encoding='utf-8') as f:
    f.write(variable_report_content)

print(f"Relatório de variáveis exportado com sucesso para: {output_path_md}")